FROM oven/bun:latest


WORKDIR /usr/ws

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json
COPY ./apps/ws-backend ./apps/ws-backend



RUN bun install
RUN bun run db:generate

EXPOSE 8081

CMD [ "bun", "run","start:ws-backend" ]
